export const mainTheme = {
  name: "maroon",
  mainBG: "#ffcccc",
  runBG: "#ccffcc",
  walkBG: "#fff8cc",
  inputContainerBG: "#800000",
  labelText: "#f5f5f5",
  inputText: "#800000",
  inputBG: "#fff",
  inputBorder: "#ccc",
  startButtonBG: "#81C784",
  pauseButtonBG: "#FFD54F",
  stopButtonBG: "#EF9A9A",
  lockButtonBG: "darkgoldenrod",
  iconStart: "#1B5E20",
  iconPause: "#996700",
  iconStop: "#8B0000",
  iconLock: "black",
  text: "RajdhaniBold",
  textColor: "black",
  iconMenu: "#800000",
  buttonShadowColor: "#00000000",
  buttonShadowOpacity: 0,
  buttonShadowRadius: 0,
  buttonShadowOffset: { width: 0, height: 0 },
  buttonElevation: 0,
};

export const blackTheme = {
  name: "black",
  mainBG: "#111111",
  runBG: "#111111",
  walkBG: "#111111",
  inputContainerBG: "#222",
  labelText: "#eeeeee",
  inputText: "#eeeeee",
  inputBG: "#444",
  inputBorder: "#666",
  startButtonBG: "#222",
  pauseButtonBG: "#222",
  stopButtonBG: "#222",
  lockButtonBG: "#222",
  iconStart: "#eeeeee",
  iconPause: "#eeeeee",
  iconStop: "#eeeeee",
  iconLock: "#eeeeee",
  text: "RajdhaniBold",
  textColor: "white",
  iconMenu: "white",
  buttonShadowColor: "#00000000",
  buttonShadowOpacity: 0,
  buttonShadowRadius: 0,
  buttonShadowOffset: { width: 0, height: 0 },
  buttonElevation: 0,
};

export const whiteTheme = {
  name: "white",
  mainBG: "#ffffff",
  runBG: "#ffffff",
  walkBG: "#ffffff",
  inputContainerBG: "#f5f5f5",
  labelText: "#333333",
  inputText: "#333333",
  inputBG: "#ffffff",
  inputBorder: "#bbbbbb",
  startButtonBG: "#f5f5f5",
  pauseButtonBG: "#f5f5f5",
  stopButtonBG: "#f5f5f5",
  lockButtonBG: "#f5f5f5",
  iconStart: "#333333",
  iconPause: "#333333",
  iconStop: "#333333",
  iconLock: "#333333",
  text: "RajdhaniBold",
  textColor: "black",
  iconMenu: "f5f5f5",
  buttonShadowColor: "#000",
  buttonShadowOpacity: 0.2,
  buttonShadowRadius: 6,
  buttonShadowOffset: { width: 0, height: 4 },
  buttonElevation: 5,
};
